acme_project/acme_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('catalog/', include('catalog.urls')),
]

acme_project/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.product_list, name='product_list'),
] 

acme_project/catalog/urls.py
from django.urls import path

from . import views

app_name = 'catalog'

urlpatterns = [
    path('<slug:category>/', views.product_detail, name="product_detail"),
    path("", views.product_list, name="product_list")
] 

acme_project/homepage/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # Если вызван URL без относительного адреса (шаблон — пустые кавычки),
    # то вызывается view-функция index() из файла views.py
    path('', views.index),
] 

acme_project/cart/models.py
from django.db import models

# Create your models here.

acme_project/cart/views.py
from django.shortcuts import render

# Create your views here.

acme_project/catalog/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def product_detail(request, category):
    return HttpResponse(f'Категория {category}')

def product_list(request):
    template_name = 'catalog/product_list.html'
    title = 'Список товаров ACME'
    products = [
      'Iron carrot',
      'Giant mousetrap',  
      'Dehydrated boulders',
      'Invisible paint',
    ]
    context = {
        'title': title,
        'products': products,
    }
    return render(request, template_name, context)

acme_project/homepage/views.py
from django.http import HttpResponse
from django.shortcuts import render

def index(request):
    # Адрес шаблона сохранён в переменную, это не обязательно, но удобно.
    template_name = 'homepage/index.html'
    # Строка, которую надо вывести на страницу, тоже сохранена в переменную.
    title = 'Главная страница ACME'
    promo_product = 'Iron carrot'
    context = {
        # Ключ словаря и имя переменной не обязательно называть одинаково,
        # но обычно это удобнее, чем использовать два разных имени.
        'title': title,
        'promo_product': promo_product,
    }
    # Третьим аргументом в render() передаём словарь context:
    return render(request, template_name, context)

acme_project/templates/base.html
<!-- base.html -->
<!DOCTYPE html>
<html lang="ru">
  <head>
  </head>
  <body>
    {% include "includes/header.html" %}
    <main>
      {% block content %}Контента пока нет :({% endblock %}
    </main>
    {% include "includes/footer.html" %}
  </body>
</html> 

acme_project/templates/catalog/product_list.html
 <!-- product_list.html --> 
 {% extends "base.html" %}
  {% block content %}
   <h1>{{ title }}</h1>
   {% for product in products %}
     <p>{{ product }}</p>
   {% if forloop.last %}
     <hr>
   {% endif %}
   {% empty %}
     <p>Нет доступных товаров.</p>
   {% endfor %} 
  {% endblock %}

acme_project/templates/homepage/index.html
 <!-- index.html --> 
 {% extends "base.html" %}
 <!-- Имя блока — content, такое же, как в базовом шаблоне --> 
 {% block content %}
   <h1>{{ title }}</h1>
   <p>Товар дня <strong>{{ promo_product }}</strong></p>

   <a href="{% url 'catalog:product_list' %}">
     Страница со списком товаров 
   </a>

    <br>

   <a href="{% url 'catalog:product_detail' 1 %}">
     Страница c товаром номер 1 
   </a> 
 {% endblock %}

acme_project/templates/includes/footer.html
<!-- footer.html -->
<footer>
  <p><i>Подвал</i></p>
</footer> 

acme_project/templates/includes/header.html
<!-- header.html -->
<header>
  <p><i>Шапка страницы</i></p>
</header> 